logsBucket: "gs://rc05logs/"

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/abcdef-1sdf/my-app', '.']
  id: 'Build Docker image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/abcdef-1sdf/my-app']
  id: 'Push Docker image to GCR'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud secrets versions access latest --secret=myapp > /tmp/ssh_key

      chmod 600 /tmp/ssh_key

      ssh-keyscan -H 34.135.79.45 >> ~/.ssh/known_hosts

      ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no rchinta3@34.135.79.45 \
        'docker pull gcr.io/abcdef-1sdf/my-app && docker run -d -p 80:80 gcr.io/abcdef-1sdf/my-app'

      rm /tmp/ssh_key
